// Bundle the API into one ESM file for the Supabase Edge Function `api` (Deno).
// Node built-ins stay external (`node:` imports); CommonJS deps like Express get a createRequire shim.
import { build } from 'esbuild';
import { builtinModules } from 'node:module';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../..', import.meta.url));
const out = root + 'supabase/functions/api/index.js';

await build({
  entryPoints: [fileURLToPath(new URL('../src/edge.ts', import.meta.url))],
  outfile: out,
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'es2022',
  minify: true,
  legalComments: 'none',
  external: [...builtinModules, ...builtinModules.map(m => 'node:' + m)],
  plugins: [{
    // Deno needs the `node:` prefix for built-ins.
    name: 'node-prefix',
    setup(b) {
      b.onResolve({ filter: new RegExp(`^(${builtinModules.join('|').replace(/\//g, '\\/')})$`) }, a => ({ path: 'node:' + a.path, external: true }));
    },
  }],
  banner: {
    js: [
      '// Generated by server/scripts/build-edge.mjs — do not edit. Rebuild with `npm run build:edge`.',
      "import { createRequire as __cr } from 'node:module'; import __process from 'node:process'; import { Buffer as __Buffer } from 'node:buffer';",
      "import { setImmediate as __si, clearImmediate as __ci } from 'node:timers';",
      'const require = __cr(import.meta.url); const __filename = "/index.js", __dirname = "/";',
      // Node globals Deno lacks: the postgres driver calls setImmediate on socket connect.
      'globalThis.process ??= __process; globalThis.Buffer ??= __Buffer; globalThis.global ??= globalThis;',
      'globalThis.setImmediate ??= __si; globalThis.clearImmediate ??= __ci;',
    ].join('\n'),
  },
  logLevel: 'info',
});
